declare const styles: {
  readonly "leaflet-disabled": string;
  readonly "leaflet-draw": string;
  readonly "leaflet-draw-actions": string;
  readonly "leaflet-draw-actions-bottom": string;
  readonly "leaflet-draw-actions-top": string;
  readonly "leaflet-draw-draw-circle": string;
  readonly "leaflet-draw-draw-circlemarker": string;
  readonly "leaflet-draw-draw-marker": string;
  readonly "leaflet-draw-draw-polygon": string;
  readonly "leaflet-draw-draw-polyline": string;
  readonly "leaflet-draw-draw-rectangle": string;
  readonly "leaflet-draw-edit-edit": string;
  readonly "leaflet-draw-edit-remove": string;
  readonly "leaflet-draw-guide-dash": string;
  readonly "leaflet-draw-section": string;
  readonly "leaflet-draw-toolbar": string;
  readonly "leaflet-draw-toolbar-nobottom": string;
  readonly "leaflet-draw-toolbar-notop": string;
  readonly "leaflet-draw-toolbar-top": string;
  readonly "leaflet-draw-tooltip": string;
  readonly "leaflet-draw-tooltip-single": string;
  readonly "leaflet-draw-tooltip-subtext": string;
  readonly "leaflet-edit-marker-selected": string;
  readonly "leaflet-edit-move": string;
  readonly "leaflet-edit-resize": string;
  readonly "leaflet-error-draw-tooltip": string;
  readonly "leaflet-mouse-marker": string;
  readonly "leaflet-oldie": string;
  readonly "leaflet-retina": string;
  readonly "leaflet-right": string;
  readonly "leaflet-touch": string;
  readonly "sr-only": string;
};
export = styles;

